### PR TITLE
Handle disconnection due to server timeout when publishing data at lo…

### PR DESCRIPTION
**Pull request by flonou**
…w frequency

### CODE REVIEW

**Review by mrpropellers — DISMISSED** [review]
No problems with this change here, but the target branch will likely need to be carefully merged into dev due to code organization changes.

**Comment by flonou** [comment]
Would you prefer that I try to rebase the fixed KeepConnection code on the current master ?

**Comment by mrpropellers** [comment]
> Would you prefer that I try to rebase the fixed KeepConnection code on the current master ?

I gave rebasing a shot today and found that it was even more garbled than I expected. I think what will make the most sense, since I've already invested several hours in getting this rebase figured out, is to wait until I can submit a corrected branch for PR tomorrow, and we re-target this PR against that.

**Comment by mrpropellers** [comment]
Alright so just to give an update: the rebase is mostly cleared up but it seems like we changed some member functions to static functions, while this PR introduced a requirement that they not be static. I'm actually just starting to dig into this portion of our codebase, so I've been giving myself the grand tour to make sure I don't break anything while I'm resolving the interface changes. Should hopefully have a complete and functional branch for you to submit this diff against sometime Monday, and I'll be sure to babysit it to make sure it gets merged before we make any new drastic changes :)

**Comment by mrpropellers** [comment]
Hey @flonou sorry for the delayed code push but I've been struggling to validate this code change against our existing example environments. Could you confirm for me how you originally tested this change?  Did you check whether your logic behaved correctly when there are multiple connections active at once?  When I run this code against our [Pick and Place example](https://github.com/Unity-Technologies/Unity-Robotics-Hub/tree/main/tutorials/pick_and_place) I find that `SendServiceMessage` simply reads whatever data is first available on its given `networkStream`, which is sometimes a message intended for a different topic, causing all sorts of I/O errors. Did you observe similar behavior?

**Comment by flonou** [comment]
Hi ! what do you mean by "multiple connections active at once" ? We have tested it on a case where the connection registers and publishes multiple topics through the same tcpendpoint. Also, this requires the corresponding branch/PR on tcpendpoint to be used (when we changed the pull request, I forgot to put that information on this one, sorry)
https://github.com/Unity-Technologies/ROS-TCP-Endpoint/pull/25

**Comment by mrpropellers** [comment]
> Hi ! what do you mean by "multiple connections active at once" ? We have tested it on a case where the connection registers and publishes multiple topics through the same tcpendpoint. Also, this requires the corresponding branch/PR on tcpendpoint to be used (when we changed the pull request, I forgot to put that information on this one, sorry)
> [Unity-Technologies/ROS-TCP-Endpoint#25](https://github.com/Unity-Technologies/ROS-TCP-Endpoint/pull/25)

Specifically, from within Unity, if we `SendServiceMessage`, the response read out of `networkStream` was not guaranteed to be the response from the service for which the function was originally called.  For example, we publish a request to the `NiryoMoveIt` service, but the  response read from the network stream during that function call was intended for the  `__handshake` service.  I'm not familiar enough with the networking stack to know whether this is an ordering problem, or an issue with stale data persisting on networkStream because it isn't being closed (and probably flushed) between requests.  The PR drafts that I'm testing on are [here](https://github.com/Unity-Technologies/ROS-TCP-Connector/pull/76/files) and [here](https://github.com/Unity-Technologies/ROS-TCP-Endpoint/pull/42/files) if you want to try it out.  It's also possible I've missed part of your original change while cleaning up the merge conflicts.

**Comment by flonou** [comment]
Oh I see, I have not tested it with services back then (It wasn't handled, or not in the same way for as far as I can see between my original PR and the drafts you linked, there was no send_unity_service methods on the tcp endpoint for example). Maybe services would need separate connections unlike publishers. The goal was to prevent opening one connection per published message so it should not have a side effect on services

Do you wish for me to start from scratch from Main Head when I find some time ?

**Comment by mrpropellers** [comment]
It's up to you how you want to proceed, but we can't merge the code as-is and we're not prioritizing this functionality as a feature internally, so we won't be doing any more work to try and get this functional. We are improving our process around handling user-submitted PR's though, so I can at least promise that if you want to submit an amended version of this change using the tip of dev, we shouldn't have any of the time issues with merge resolution or getting it in in a timely manner.

**Comment by unity-cla-assistant** [comment]
[CLA assistant check](https://cla-assistant.cds.internal.unity3d.com/Unity-Technologies/ROS-TCP-Connector?pullRequest=70) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.cds.internal.unity3d.com/Unity-Technologies/ROS-TCP-Connector?pullRequest=70) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.cds.internal.unity3d.com/check/Unity-Technologies/ROS-TCP-Connector?pullRequest=70) it.</sub>

**Pull request closed without merging**
