### PR TITLE
Laurie/ux feedback

### PR DESCRIPTION
**Pull request by LaurieCheers-unity**
Implementing comments from items 10 and 12 of https://docs.google.com/document/d/1NXAUDnzS8AIMpRMRNUh4lreBuG6Mus_VRn5_idSx9f0/edit#

### CODE REVIEW

**Comment by mpinol** [comment]
Addressing Issue #10, now that we have the browser would it make sense to remove the auto generate action, messages, and services options from the menu?

**Comment by LaurieCheers-unity** [comment]
> Addressing Issue 10, now that we have the browser would it make sense to remove the auto generate action, messages, and services options from the menu?

Yeah, I just talked to Sarah about that; agree, we should remove the other menu items. I'll adjust the PR.

**Comment by at669** [comment]
> > Addressing Issue 10, now that we have the browser would it make sense to remove the auto generate action, messages, and services options from the menu?
> 
> Yeah, I just talked to Sarah about that; agree, we should remove the other menu items, although that means changing the tutorial too. I'll do that in a separate PR.

in that case, I will hold off on Unity-Technologies/Unity-Robotics-Hub#88 to update the tutorial and screenshots accordingly

**Comment by LaurieCheers-unity** [comment]
Ok, the new PR is https://github.com/Unity-Technologies/ROS-TCP-Connector/pull/42

**Pull request merged**
