### PR TITLE
GetBytes function defaults conversion of bytes to shorts. Adding expl…

### PR DESCRIPTION
**Pull request by mpinol**
…icit serializaton line for bytes.

### CODE REVIEW

**Review by LaurieCheers-unity — CHANGES_REQUESTED** [review]
You only changed the GenerateSerialization section, there's a corresponding GenerateDeserialization above that should stay in sync.

**Comment by mpinol** [comment]
> You only changed the GenerateSerialization section, there's a corresponding GenerateDeserialization above that should stay in sync.

Should already be handled here, https://github.com/Unity-Technologies/ROS-TCP-Connector/blob/d63e0246320eabb8e181229ae8d17fdc31d1aec4/Runtime/MessageGeneration/MessageParser.cs#L654

**Comment by LaurieCheers-unity** [comment]
> > You only changed the GenerateSerialization section, there's a corresponding GenerateDeserialization above that should stay in sync.
> 
> Should already be handled here,
> 
> https://github.com/Unity-Technologies/ROS-TCP-Connector/blob/d63e0246320eabb8e181229ae8d17fdc31d1aec4/Runtime/MessageGeneration/MessageParser.cs#L654

Well that's even worse... the numericTypeDeserializationFunctions list handles 12 different types ("sbyte","byte","bool","char","double","short","int","long","float","ushort", "uint", "ulong"), but we only know how to serialize 2 of them? This class is a mess. I suggest we need a corresponding numericTypeSerializationFunctions list.

**Comment by mpinol** [comment]
> numericTypeDeserializationFunctions

This class could definitely do with a refactor but what do mean by `we only know how to serialize 2 of them? `  exactly?

**Comment by LaurieCheers-unity** [comment]
Ok, so the class definitely needs refactoring but I can see this change is a step in the right direction.

**Review by LaurieCheers-unity — APPROVED** [review]

**Pull request merged**
